remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
future: false
show_drafts: 'false'
locale: en-US
title: Cryptocurrency Ramblings
title_separator: '-'
name: Dennis Rutjes
description: A journey towards crypto currency trading.
url: 'https://cryptocurrency.ramblings.news'
baseurl: null
repository: 'DennisRutjes/cryptocurrency.ramblings'
teaser: null
words_per_minute: 200
comments:
  provider: 'staticman_v2'
  disqus:
    shortname: null
  discourse:
    server: null
  facebook:
    appid: null
    num_posts: null
    colorscheme: null
staticman:
  branch: "master"
  moderation: true
  path: "_data/comments/{options.slug}"
  commitMessage: "New comment by {fields.name}"
  allowedFields: ["name", "email", "url", "message","replying_to"]
  filename: "comment-{@timestamp}"
  format: "yaml"
  generatedFields:
    date:
      type: date
      options:
        format: "timestamp-milliseconds"
  requiredFields: ["name", "email", "message"]
  transforms:
    email: md5
  # reCaptcha
  # Register your domain at https://www.google.com/recaptcha/ and choose reCAPTCHA V2
reCaptcha:
  enabled: false
  siteKey: "6Lfo_GkUAAAAAOLurRwH8R9RT4S-tszQElzujhDY"
  # Encrypt reCaptcha secret key using Staticman /encrypt endpoint
  # For more information, https://staticman.net/docs/encryption
  secret: "Ro6UZAQ7UtlPier1feIGOAel/ZxmjMCW6TiaPlQWh5cRUA9W6tcyLKfQ2wqjYl8VyVTZ06Yl0WAaVpn0Z6NGt30NY5zVmxuYNcVOn74yztnsflShIUaDsJCrRUtENTnj01PTS/3XpWFZOt/h9WXvy9+yrzyXiSc0vJzxoXJiU04="
atom_feed:
  path: null
search: true
search_full_content: null
search_provider: lunr
algolia:
  application_id: null
  index_name: null
  search_only_api_key: null
  powered_by: null
google:
  search_engine_id: null
  instant_search: null
google_site_verification: null
bing_site_verification: null
yandex_site_verification: null
naver_site_verification: null
twitter:
  username: null
facebook:
  username: null
  app_id: null
  publisher: null
og_image: null
social:
  type: null
  name: null
  links: null
analytics:
  provider: google
  google:
    tracking_id: UA-123885608-1
    anonymize_ip: null
author:
  name: Dennis Rutjes
  avatar: /assets/images/bio-photo.jpg
  bio: >-
    Experienced Craftsman with a demonstrated history of working in the IT and
    services industry. Dabbling with crypto currency trade as a hobby. 
  location: 'The Netherlands, GD'
  email: null
  uri: 'https://www.binance.com/?ref=35360148'
  home: null
  bitbucket: null
  codepen: null
  dribbble: null
  flickr: null
  facebook: null
  foursquare: null
  github: null
  gitlab: null
  google_plus: null
  keybase: null
  instagram: null
  lastfm: null
  linkedin: null
  pinterest: null
  soundcloud: null
  stackoverflow: null
  steam: null
  tumblr: null
  twitter: RamblingsN
  vine: null
  weibo: null
  xing: null
  youtube: null
include:
- .htaccess
- _pages
exclude:
- '*.sublime-project'
- '*.sublime-workspace'
- vendor
- .asset-cache
- .bundle
- .jekyll-assets-cache
- .sass-cache
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
keep_files:
- .git
- .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+


incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
paginate: 5
paginate_path: '/blog/page:num/'
timezone: null
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-remote-theme
- jekyll_admin
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-remote-theme
- jekyll_admin
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: true
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
